### PR TITLE
Added options for offset, resize handler and horizontal support

### PR DESCRIPTION
**Pull request by meriouma**

### CODE REVIEW

**Comment by jDramaix** [comment]
What happens if the element is in a scroll panel ? :-)

**Comment by meriouma** [comment]
Hmm,probably not going to work. I'd have to listen to any scroll event. Maybe I could find the parents with overflow values of scroll or auto and bind a handler to those elements?

**Comment by meriouma** [comment]
I've tried something with #3

**Comment by christiangoudreau** [comment]
Did you create some tests?

**Comment by meriouma** [comment]
I'm not sure which kind of automated tests I should write for this. I think most of the tests would involve scrolling, I'm not sure if selenium could be better than a GWTTestCase?

**Comment by christiangoudreau** [comment]
Yeah, selenium test case for this would be the best I think

**Comment by meriouma** [comment]
Will work on it next week end, I probably won't have much free time this week.. :P

**Comment by christiangoudreau** [comment]
Sounds good :dancer:

**Comment by jDramaix** [comment]
LGTM

**Pull request merged**
